### ISSUE TITLE
Having sorting options in the column headings instead of explicit sorting option

### ISSUE THREAD

**Issue by prabh1601** [CodeTiger927/USACO-Rating#9]
Instead of having a another option to sort things (according to something), implement this feature in the columns headings itself.

![Screenshot-20210529091728-725x59](https://user-images.githubusercontent.com/56677063/120057231-1ca60300-c05f-11eb-8310-0eb2deae1c56.png)

The above shot is from cf for reference of what I mean(notice the arrows in the cells).

![Screenshot-20210529091748-744x49](https://user-images.githubusercontent.com/56677063/120057223-0b5cf680-c05f-11eb-8566-4ad381ffe100.png)

Same thing here would be more convinient.

**Comment by prabh1601** [comment]
Hello ! Any updates on this ? :O

**Comment by CodeTiger927** [comment]
> Hello ! Any updates on this ? :O

Oops >.< my school ends tomorrow, and I will start bringing many major updates very soon :D

**Comment by CodeTiger927** [comment]
Okay, I just added it :D can you test it and see if it works? If so you can close the issue >.<

**Comment by prabh1601** [comment]
Yep works perfect! Thanks :)
